#!/usr/bin/env python3
"""
core/ai_commander.py — Full AI control plane for HANOON.

When AI_FULL_CONTROL is enabled, EVERY decision, log line, journal entry,
notification, sizing calculation, and P&L narrative is generated by the
AI brain (Ollama + PPO ensemble). Static rule fallbacks are disabled.

Hard guardrails ($50 max loss, position limits) still clamp AI outputs.
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, TYPE_CHECKING

import numpy as np
import pandas as pd

from core.config import BotConfig
from core.notify import log
from core.pilot_mode import generative_think, get_effective_confidence_threshold
from core.human_cognition import enrich_prompt, apply_gut_override
from core.live_ai_pipeline import (
    LiveAILine,
    entry_fingerprint,
    position_fingerprint,
    exit_fingerprint,
    merge_entry_decision,
    scan_fingerprint,
)

if TYPE_CHECKING:
    from core.cognitive_autopilot import CognitiveAutopilot
    from core.consciousness import AIConsciousness


def _parse_float_price(value: Any, default: float) -> float:
    """Parse AI JSON numbers that may include $ or commas."""
    if value is None:
        return default
    if isinstance(value, (int, float)):
        return float(value)
    try:
        cleaned = str(value).strip().replace("$", "").replace(",", "")
        return float(cleaned) if cleaned else default
    except (TypeError, ValueError):
        return default

DECISION_LOG = Path("models/ai_decision_log.jsonl")
TRADE_JOURNAL = Path("models/trade_journal.json")


def _parse_json_response(raw: str) -> Dict[str, Any]:
    if not raw:
        return {}
    try:
        start = raw.find("{")
        end = raw.rfind("}") + 1
        if start >= 0 and end > start:
            return json.loads(raw[start:end])
    except Exception:
        pass
    return {}


# Live trading tasks always use the priority Ollama path (no rate-limit deferral).
_DECISION_TASKS = frozenset({
    "entry_decision", "position_manage", "exit_decision", "scan_score",
    "gut_check", "decide", "exit", "account_eval", "account_brief",
})


class AICommander:
    """Single brain for all live trading decisions and narratives."""

    def __init__(
        self,
        cfg: BotConfig,
        autopilot: Optional["CognitiveAutopilot"] = None,
        consciousness: Optional["AIConsciousness"] = None,
        model=None,
        ai_components: Optional[Dict] = None,
    ):
        self.cfg = cfg
        self.autopilot = autopilot
        self.consciousness = consciousness
        self.model = model
        self.ai_components = ai_components or {}
        self._cache: Dict[str, Tuple[float, Any]] = {}
        self._trade_journal: List[Dict] = []
        self._live_line = LiveAILine(cfg, self._ollama_decide_raw)
        DECISION_LOG.parent.mkdir(parents=True, exist_ok=True)
        self._load_journal()

    @property
    def full_control(self) -> bool:
        return bool(getattr(self.cfg, "AI_FULL_CONTROL", True))

    def _load_journal(self):
        if TRADE_JOURNAL.exists():
            try:
                self._trade_journal = json.loads(TRADE_JOURNAL.read_text())
            except Exception:
                self._trade_journal = []

    def _save_journal(self):
        try:
            TRADE_JOURNAL.write_text(json.dumps(self._trade_journal[-500:], indent=2))
        except Exception:
            pass

    def think(self, prompt: str, task: str = "reason") -> str:
        if self.autopilot and getattr(self.autopilot, "core", None):
            try:
                return (self.autopilot.core.think(prompt, task=task) or "").strip()
            except Exception:
                pass
        return generative_think(self.cfg, self.autopilot, prompt)

    def _ollama_decide_raw(self, full_prompt: str) -> str:
        """Direct priority Ollama call — bypasses rate limit for trading decisions."""
        ollama = None
        if self.autopilot and getattr(self.autopilot, "core", None):
            ollama = getattr(self.autopilot.core, "ollama", None)
        if ollama and hasattr(ollama, "decide_call"):
            try:
                return (ollama.decide_call(full_prompt) or "").strip()
            except Exception as exc:
                log.debug(f"Ollama decide: {exc}")
        return ""

    def compose_telegram(self, prompt: str) -> str:
        """Dedicated Ollama path for Telegram — bypasses 30s trading rate limit."""
        ollama = None
        if self.autopilot and getattr(self.autopilot, "core", None):
            ollama = getattr(self.autopilot.core, "ollama", None)
        if ollama and hasattr(ollama, "compose_notification"):
            try:
                return (ollama.compose_notification(prompt) or "").strip()
            except Exception as exc:
                log.debug(f"AI telegram notify: {exc}")
        return self.think(prompt)

    def _mood_context(self) -> tuple:
        if self.autopilot and getattr(self.autopilot, "core", None):
            st = self.autopilot.core.state
            return st.mood, st.confidence, list(st.learned_lessons)
        return "awake", 0.5, []

    def _human_think(self, task: str, context: Dict[str, Any]) -> str:
        mood, conf, lessons = self._mood_context()
        prompt = enrich_prompt(task, context, self.cfg, mood, conf, lessons)
        return self.think(prompt)

    def think_json_live(
        self,
        ticker: str,
        task: str,
        prompt: str,
        fingerprint: str,
    ) -> Dict[str, Any]:
        """
        Non-blocking live Ollama — ring async + consume fresh result only.
        Never uses TTL cache; stale fingerprints are discarded.
        """
        mood, conf, lessons = self._mood_context()
        full = enrich_prompt(task, {"request": prompt[:2500]}, self.cfg, mood, conf, lessons)
        self._live_line.ring(ticker, task, full, fingerprint)
        live = self._live_line.consume(ticker, task, fingerprint)
        return live.get("parsed") or {}

    def live_status(self, ticker: str, task: str) -> Dict[str, Any]:
        return self._live_line.status(ticker, task)

    def prefetch_entry_decision(
        self,
        ticker: str,
        current_px: float,
        spike_ratio: float,
        scan_score: float,
        ppo_action: int = 0,
        ppo_conf: float = 0.5,
        ppo_reason: str = "",
        market_ctx: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Keep Ollama hotline open on watchlist — non-blocking."""
        if not getattr(self.cfg, "LIVE_AI_PIPELINE_ENABLED", True):
            return
        mctx = market_ctx or {}
        prompt = (
            f"DECIDE ENTRY for {ticker} @ ${current_px:.4f}\n"
            f"Volume spike {spike_ratio:.2f}x | Scan score {scan_score:.0f}\n"
            f"PPO entry signal: action={ppo_action} conf={ppo_conf:.2f} reason={ppo_reason[:80]}\n"
            f"Bid ${mctx.get('bid') or 0:.4f} Ask ${mctx.get('ask') or 0:.4f} "
            f"Spread {mctx.get('spread_pct', 0):.2%}\n"
            "You are the pilot on the LIVE hotline. JSON only:\n"
            '{"enter":true/false,"confidence":0-1,"gut_feel":0-1,"intuition":"brief",'
            '"reason":"why","journal":"log"}'
        )
        fp = entry_fingerprint(ticker, current_px, spike_ratio, scan_score)
        mood, conf, lessons = self._mood_context()
        full = enrich_prompt("entry_decision", {"request": prompt[:2500]}, self.cfg, mood, conf, lessons)
        self._live_line.ring(ticker, "entry_decision", full, fp)

    def think_json(self, prompt: str, cache_key: str = "", ttl: float = 2.0,
                   task: str = "decide") -> Dict[str, Any]:
        """Blocking path — only for non-live tasks (journals, rankings)."""
        if getattr(self.cfg, "LIVE_AI_PIPELINE_ENABLED", True) and task in _DECISION_TASKS:
            log.debug(f"think_json blocked for live task {task} — use think_json_live")
            return {}

        if cache_key and cache_key in self._cache:
            ts, val = self._cache[cache_key]
            if val and time.time() - ts < ttl:
                return val

        mood, conf, lessons = self._mood_context()
        full = enrich_prompt(task, {"request": prompt[:2500]}, self.cfg, mood, conf, lessons)
        raw = self.think(full, task=task)
        parsed = _parse_json_response(raw)
        if cache_key and parsed:
            self._cache[cache_key] = (time.time(), parsed)
        return parsed

    def journal(self, category: str, message: str, data: Optional[Dict] = None):
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "category": category,
            "message": message,
            "data": data or {},
        }
        try:
            with open(DECISION_LOG, "a") as f:
                f.write(json.dumps(entry) + "\n")
        except Exception:
            pass
        if self.consciousness:
            try:
                self.consciousness._write_thought(category, message, data)
            except Exception:
                pass
        if self.autopilot:
            try:
                self.autopilot.observe_market_event({"type": category, "message": message, **(data or {})})
            except Exception:
                pass

    def _fast_log_line(self, category: str, context: Dict[str, Any]) -> str:
        """Structured log line — no Ollama (hot path must not block IB loop)."""
        if category == "LIVE_PULSE":
            t = context.get("ticker", "?")
            px = context.get("price", 0)
            pnl = context.get("pnl_usd", 0)
            pct = context.get("pnl_pct", 0)
            return (
                f"🧠 LIVE_PULSE: {t} ${px:.4f} | P&L ${pnl:+.2f} ({pct:+.2f}%) | "
                f"Stop ${context.get('stop', 0):.4f} | TP ${context.get('target', 0):.4f}"
            )
        return f"🧠 {category}: {json.dumps(context, default=str)[:120]}"

    def ai_log(self, category: str, context: Dict[str, Any], level: str = "info"):
        """AI writes the log line itself."""
        if not self.full_control:
            return
        # Hot-path categories: never block the trading loop on Ollama
        hot = {"LIVE_PULSE", "STOP_UPDATE", "TP_UPDATE", "TRAIL_UPDATE"}
        if category in hot:
            line = self._fast_log_line(category, context)
            getattr(log, level, log.info)(line)
            self.journal(category, line, context)
            return
        prompt = (
            f"You are HANOON trading AI. Write ONE concise log line for category '{category}'.\n"
            f"Context: {json.dumps(context, default=str)[:800]}\n"
            "Include emoji, key numbers, and reasoning. Max 160 chars. No JSON."
        )
        line = self.think(prompt) or f"🧠 {category}: {context.get('summary', '')}"
        line = line.strip().split("\n")[0][:200]
        getattr(log, level, log.info)(line)
        self.journal(category, line, context)

    def notify(self, notifier, event_type: str, context: Dict[str, Any]):
        """AI-only notification — delegates to Telegram AI composer."""
        from core.ai_notifier import send_smart_telegram
        fallback = f"🧠 {event_type}: {json.dumps(context, default=str)[:120]}"
        send_smart_telegram(
            notifier, event_type, context, fallback,
            ai_commander=self,
            autopilot=self.autopilot,
            consciousness=self.consciousness,
        )

    def ppo_action(self, obs: np.ndarray, bar_df: Optional[pd.DataFrame] = None,
                   for_entry: bool = False) -> Tuple[int, float, str]:
        if self.model is None or not self.ai_components:
            return 0, 0.5, "no model"
        try:
            from core.agent import predict_with_reasoning
            action, conf, reason = predict_with_reasoning(
                self.model, obs, self.cfg, self.ai_components, bar_df=bar_df,
                for_entry=for_entry,
            )
            return action, conf, reason or ""
        except Exception as exc:
            return 0, 0.5, str(exc)

    def score_ticker(self, ticker: str, df: pd.DataFrame, hints: Optional[Dict] = None) -> Dict[str, Any]:
        """AI scores a ticker for scan ranking (replaces static scoring when full control)."""
        hints = hints or {}
        if not self.full_control:
            return hints

        closes = df["close"].values
        vols = df["volume"].values
        px = float(closes[-1])
        ret5 = (closes[-1] / closes[-6] - 1) * 100 if len(closes) > 5 else 0
        vol_ratio = float(np.mean(vols[-5:])) / (float(np.mean(vols[-20:])) + 1e-9)

        prompt = (
            f"Score ticker {ticker} for intraday momentum scalp 0-100.\n"
            f"Price ${px:.4f} | 5bar ret {ret5:.2f}% | vol_ratio {vol_ratio:.2f}x\n"
            f"Rule hints: {json.dumps(hints, default=str)[:300]}\n"
            "Use computational analysis AND gut feel — does this stock feel tradeable right now?\n"
            'JSON only: {"score":0-100,"enter_bias":true/false,"reasons":"brief",'
            '"confidence":0-1,"gut_feel":0-1,"intuition":"one sentence"}'
        )
        fp = scan_fingerprint(ticker, px, vol_ratio)
        if getattr(self.cfg, "LIVE_AI_PIPELINE_ENABLED", True):
            mood, conf, lessons = self._mood_context()
            full = enrich_prompt(
                "scan_score", {"request": prompt[:2500]}, self.cfg, mood, conf, lessons,
            )
            self._live_line.ring(ticker, "scan_score", full, fp)
            live = self._live_line.consume(ticker, "scan_score", fp)
            out = live.get("parsed") or {}
            if live.get("status") != "fresh":
                out = {}
        else:
            out = self.think_json(prompt, cache_key=f"score_{ticker}", ttl=5.0, task="scan_score")
        score = float(out.get("score", hints.get("total_score", 0)) or 0)
        reasons = str(out.get("reasons", hints.get("reasons", "ai_score")))
        self.journal("SCAN_SCORE", f"{ticker} score={score:.0f}", {"ticker": ticker, "score": score, "out": out})
        return {
            "ticker": ticker,
            "price": px,
            "volume": int(vols[-1]),
            "avg_volume": int(np.mean(vols[-20:])),
            "rel_vol": round(vol_ratio, 2),
            "total_score": round(score, 1),
            "reasons": reasons,
            "ai_score": round(score, 1),
            "confidence": float(out.get("confidence", 0.5)),
        }

    def decide_entry(
        self,
        ticker: str,
        df: pd.DataFrame,
        current_px: float,
        spike_ratio: float,
        scan_score: float,
        account: Dict[str, Any],
        obs: Optional[np.ndarray] = None,
        bar_df: Optional[pd.DataFrame] = None,
        pilot=None,
        market_ctx: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """AI decides entry, sizing, stop, target — guardrails clamp output."""
        ppo_action, ppo_conf, ppo_reason = (0, 0.5, "")
        if obs is not None:
            ppo_action, ppo_conf, ppo_reason = self.ppo_action(obs, bar_df, for_entry=True)

        deploy_cap = float(getattr(self.cfg, "DEPLOY_PER_STOCK_USD", 1000))
        max_risk = 50.0
        min_conf = get_effective_confidence_threshold(self.cfg, pilot)
        mctx = market_ctx or {}
        bid = mctx.get("bid")
        ask = mctx.get("ask")
        spread = mctx.get("spread_pct", 0)
        avg_vol = mctx.get("avg_volume", 0)
        penny_thr = float(getattr(self.cfg, "PENNY_PRICE_THRESHOLD", 1.0))
        is_penny = current_px < penny_thr

        prompt = (
            f"DECIDE ENTRY for {ticker} @ ${current_px:.4f}\n"
            f"Volume spike {spike_ratio:.2f}x | Scan score {scan_score:.0f}\n"
            f"PPO entry signal: action={ppo_action} conf={ppo_conf:.2f} reason={ppo_reason[:80]}\n"
            f"Account: equity ${account.get('equity', 0):,.0f} cash ${account.get('cash', 0):,.0f}\n"
            f"Max deploy ${deploy_cap:.0f} | Max risk ${max_risk:.0f}\n"
            f"Bid ${bid or 0:.4f} Ask ${ask or 0:.4f} Spread {spread:.2%} | Avg vol {avg_vol:,.0f}\n"
            + (
                "PENNY STOCK: IB rejects large MARKET orders (error 2161). "
                "Use smaller size — max deploy $350, max ~1200 shares. Limit entry only.\n"
                if is_penny else ""
            )
            + "You are the pilot. Use ALL computational data AND your gut feel like a veteran trader.\n"
            "Analyze momentum, slippage risk, liquidity, and whether this setup feels right.\n"
            'JSON: {"enter":true/false,"confidence":0-1,"gut_feel":0-1,"intuition":"gut read",'
            '"shares":N,"stop":price,"target":price,"reason":"why","journal":"first-person pilot log"}'
        )
        fp = entry_fingerprint(ticker, current_px, spike_ratio, scan_score)
        pipeline_on = getattr(self.cfg, "LIVE_AI_PIPELINE_ENABLED", True)

        if pipeline_on:
            mood, conf_m, lessons = self._mood_context()
            full = enrich_prompt(
                "entry_decision", {"request": prompt[:2500]}, self.cfg, mood, conf_m, lessons,
            )
            self._live_line.ring(ticker, "entry_decision", full, fp)
            live = self._live_line.consume(ticker, "entry_decision", fp)
            merged = merge_entry_decision(
                live.get("parsed") or {},
                live.get("status", "missing"),
                ppo_action, ppo_conf, ppo_reason, min_conf,
            )
            out = merged
            enter = bool(out.get("enter"))
            confidence = float(out.get("confidence", ppo_conf))
            if live.get("status") == "fresh":
                gut_feel = float(out.get("gut_feel", 0.5) or 0.5)
                intuition = str(out.get("intuition", ""))[:120]
                enter, gut_note = apply_gut_override(enter, gut_feel, ppo_action, ppo_conf, min_conf)
                if gut_note:
                    out["reason"] = f"{out.get('reason', '')} | {gut_note}".strip(" |")
                if intuition:
                    out["journal"] = f"{intuition} — {out.get('journal', '')}"[:300]
        else:
            out = self.think_json(
                prompt, cache_key=f"entry_{ticker}",
                ttl=float(getattr(self.cfg, "OLLAMA_MIN_CALL_INTERVAL_SEC", 1.0)),
                task="entry_decision",
            )
            if not out:
                enter = ppo_action == 1 and ppo_conf >= min_conf
                confidence = ppo_conf
                out = {
                    "reason": ppo_reason or f"PPO ensemble conf={ppo_conf:.0%} (Ollama offline)",
                    "journal": f"PPO ensemble: spike {spike_ratio:.1f}x score {scan_score:.0f}",
                }
            else:
                enter = bool(out.get("enter", ppo_action == 1))
                confidence = float(out.get("confidence", ppo_conf) or ppo_conf)
                gut_feel = float(out.get("gut_feel", 0.5) or 0.5)
                intuition = str(out.get("intuition", ""))[:120]
                enter, gut_note = apply_gut_override(enter, gut_feel, ppo_action, ppo_conf, min_conf)
                if gut_note:
                    out["reason"] = f"{out.get('reason', '')} | {gut_note}".strip(" |")
                if intuition:
                    out["journal"] = f"{intuition} — {out.get('journal', '')}"[:300]
                if self.full_control and not enter and ppo_action == 1 and ppo_conf >= min_conf * 0.85:
                    enter = True
                    confidence = max(confidence, ppo_conf)
                    out["reason"] = f"PPO+AI ensemble: {ppo_reason}"

        # Momentum scalp override — strong scanner + volume spike (uptrend already confirmed)
        if not enter:
            if spike_ratio >= 1.5 and scan_score >= 35:
                enter = True
                confidence = max(confidence, 0.55)
                out["reason"] = (
                    f"Momentum entry: spike={spike_ratio:.1f}x score={scan_score:.0f} | "
                    f"{out.get('reason', ppo_reason or '')}"
                )[:200]
            elif spike_ratio >= 1.3 and scan_score >= 45 and ppo_conf >= min_conf * 0.75:
                enter = True
                confidence = max(confidence, ppo_conf)
                out["reason"] = (
                    f"Scanner+AI: score={scan_score:.0f} spike={spike_ratio:.1f}x | "
                    f"{ppo_reason or ''}"
                )[:200]
            elif ppo_action == 1 and ppo_conf >= min_conf:
                enter = True
                confidence = max(confidence, ppo_conf)
                out["reason"] = f"PPO buy signal: {ppo_reason or 'ensemble confirmed'}"

        shares = int(_parse_float_price(out.get("shares", 0), 0))
        if shares < 1:
            shares = max(1, int(deploy_cap / current_px))

        # Liquidity / penny caps — prevent IB regulatory order rejection (2161)
        if is_penny:
            penny_deploy = float(getattr(self.cfg, "PENNY_MAX_DEPLOY_USD", 350.0))
            shares = min(shares, max(1, int(penny_deploy / current_px)))
            shares = min(shares, int(getattr(self.cfg, "PENNY_MAX_SHARES", 1200)))
        if avg_vol > 0:
            vol_cap = max(1, int(avg_vol * float(getattr(self.cfg, "LIQUIDITY_MAX_VOL_PCT", 0.08))))
            if shares > vol_cap:
                shares = vol_cap
                out["reason"] = f"{out.get('reason', '')} | liquidity cap {vol_cap} sh".strip(" |")

        # Clamp stop to valid range — penny stocks can't have $50/share stop distance
        stop_dist_raw = max_risk / max(shares, 1)
        min_dist = current_px * float(getattr(self.cfg, "SCALP_MIN_STOP_PCT", 0.004))
        max_dist = current_px * float(getattr(self.cfg, "SCALP_MAX_STOP_PCT", 0.015))
        stop_dist = float(max(min_dist, min(stop_dist_raw, max_dist)))
        default_stop = current_px - stop_dist
        stop = _parse_float_price(out.get("stop"), default_stop)
        stop = max(stop, current_px - max_dist)
        stop = min(stop, current_px * 0.995)
        stop = max(stop, 0.0001)

        min_tp = current_px + stop_dist * float(getattr(self.cfg, "SCALP_MIN_RR", 1.5))
        max_tp = current_px + current_px * float(getattr(self.cfg, "SCALP_MAX_TP_PCT", 0.03))
        target = _parse_float_price(out.get("target"), min_tp)
        target = max(target, min_tp, current_px * 1.005)
        target = min(target, max_tp)

        actual_risk = (current_px - stop) * shares

        reason = str(out.get("reason", ppo_reason or "AI entry"))
        journal_note = str(out.get("journal", reason))[:300]

        decision = {
            "enter": enter,
            "confidence": confidence,
            "shares": shares,
            "stop": round(stop, 4),
            "target": round(target, 4),
            "risk_usd": round(min(max_risk, actual_risk), 2),
            "reason": reason,
            "journal": journal_note,
        }
        self.journal("ENTRY_DECISION", journal_note, decision)
        self.ai_log("ENTRY_DECISION", {**decision, "ticker": ticker, "price": current_px})
        return decision

    def decide_position_manage(self, ctx: Dict[str, Any]) -> Dict[str, Any]:
        """AI manages open position: stop/TP/exit — async Ollama hotline."""
        ticker = str(ctx.get("ticker", "?"))
        price = float(ctx.get("price", 0) or 0)
        pnl_pct = float(ctx.get("pnl_pct", 0) or 0)
        stop = float(ctx.get("stop", 0) or 0)
        target = float(ctx.get("target", 0) or 0)
        fp = position_fingerprint(ticker, price, pnl_pct, stop, target)
        prompt = (
            "You are HANOON live pilot managing an OPEN position. Full autonomy.\n"
            f"{json.dumps(ctx, default=str)[:900]}\n"
            "Use computational analysis (volatility, P&L, regime) AND gut feel — "
            "does this trade still feel alive or is it dying?\n"
            'JSON: {"action":"HOLD|WIDEN_STOP|TIGHTEN_STOP|RAISE_TP|EXIT",'
            '"stop":price,"target":price,"confidence":0-1,"gut_feel":0-1,'
            '"intuition":"gut read","reason":"brief","journal":"log line"}'
        )
        if getattr(self.cfg, "LIVE_AI_PIPELINE_ENABLED", True):
            mood, conf, lessons = self._mood_context()
            full = enrich_prompt(
                "position_manage", {"request": prompt[:2500]}, self.cfg, mood, conf, lessons,
            )
            self._live_line.ring(ticker, "position_manage", full, fp)
            live = self._live_line.consume(ticker, "position_manage", fp)
            out = live.get("parsed") or {}
            if live.get("status") != "fresh":
                out = {
                    "action": "HOLD",
                    "reason": f"Ollama hotline {live.get('status', 'pending')} — PPO guard active",
                    "journal": "",
                }
        else:
            out = self.think_json(prompt, task="position_manage")
        action = str(out.get("action", "HOLD")).upper()
        if action not in ("HOLD", "WIDEN_STOP", "TIGHTEN_STOP", "RAISE_TP", "EXIT"):
            action = "HOLD"
        result = {
            "action": action,
            "stop": _parse_float_price(out.get("stop"), float(ctx.get("stop", 0) or 0)),
            "target": _parse_float_price(out.get("target"), float(ctx.get("target", 0) or 0)),
            "confidence": float(out.get("confidence", 0.5)),
            "reason": str(out.get("reason", ""))[:120],
            "journal": str(out.get("journal", ""))[:200],
        }
        if result["journal"]:
            self.journal("POSITION", result["journal"], {**ctx, **result})
        return result

    def decide_exit(self, ctx: Dict[str, Any], obs: Optional[np.ndarray] = None,
                    bar_df: Optional[pd.DataFrame] = None) -> Dict[str, Any]:
        ppo_exit, ppo_conf, ppo_reason = (False, 0.5, "")
        if obs is not None:
            action, conf, reason = self.ppo_action(obs, bar_df)
            ppo_exit = action == 2 and conf >= float(self.cfg.CONFIDENCE_THRESHOLD)
            ppo_conf, ppo_reason = conf, reason

        prompt = (
            f"Should we EXIT position {ctx.get('ticker')} now?\n"
            f"{json.dumps(ctx, default=str)[:700]}\n"
            f"PPO exit signal: {ppo_exit} conf={ppo_conf:.2f} {ppo_reason[:60]}\n"
            'JSON: {"exit":true/false,"confidence":0-1,"reason":"why","journal":"exit log"}'
        )
        ticker = str(ctx.get("ticker", "?"))
        price = float(ctx.get("price", ctx.get("current_px", 0)) or 0)
        pnl_pct = float(ctx.get("pnl_pct", 0) or 0)
        fp = exit_fingerprint(ticker, price, pnl_pct)
        if getattr(self.cfg, "LIVE_AI_PIPELINE_ENABLED", True):
            mood, conf, lessons = self._mood_context()
            full = enrich_prompt(
                "exit_decision", {"request": prompt[:2500]}, self.cfg, mood, conf, lessons,
            )
            self._live_line.ring(ticker, "exit_decision", full, fp)
            live = self._live_line.consume(ticker, "exit_decision", fp)
            out = live.get("parsed") or {}
            if live.get("status") != "fresh":
                should_exit = ppo_exit
                out = {"exit": should_exit, "confidence": ppo_conf, "reason": ppo_reason}
            else:
                should_exit = bool(out.get("exit", ppo_exit))
        else:
            out = self.think_json(prompt, ttl=1.0, task="exit_decision")
            should_exit = bool(out.get("exit", ppo_exit))
        if ppo_exit and self.full_control:
            should_exit = True
        result = {
            "exit": should_exit,
            "confidence": float(out.get("confidence", ppo_conf)),
            "reason": str(out.get("reason", ppo_reason)),
            "journal": str(out.get("journal", ""))[:200],
        }
        if should_exit:
            self.journal("EXIT_DECISION", result["journal"] or result["reason"], {**ctx, **result})
        return result

    def record_trade(self, trade: Dict[str, Any]):
        """AI journals closed trade and updates narrative P&L."""
        self._trade_journal.append(trade)
        self._save_journal()
        prompt = (
            f"Write a pilot trade journal entry for closed trade:\n"
            f"{json.dumps(trade, default=str)[:500]}\n"
            "2 sentences: what happened, lesson learned. First person as AI pilot."
        )
        note = self.think(prompt) or f"Closed {trade.get('ticker')} P&L ${trade.get('pnl_usd', 0):+.2f}"
        self.journal("TRADE_CLOSED", note[:400], trade)
        if self.autopilot:
            try:
                self.autopilot.observe_trade(trade)
            except Exception:
                pass

    def account_narrative(self, metrics: Dict[str, Any]) -> str:
        prompt = (
            "Summarize live account state for dashboard (2 sentences, pilot voice):\n"
            f"{json.dumps(metrics, default=str)[:600]}"
        )
        return (self.think(prompt) or "").strip()[:400]

    def rank_scan_results(self, results: List[Dict]) -> List[Dict]:
        """AI re-ranks scan pool."""
        if not results or not self.full_control:
            return results
        top = results[:15]
        prompt = (
            "Rank these tickers best-to-worst for immediate scalp entry. Return JSON array of tickers only.\n"
            f"{json.dumps([{'t': r['ticker'], 's': r.get('total_score', 0)} for r in top])}\n"
            'JSON: {"ranked":["TICK1","TICK2",...],"reason":"brief"}'
        )
        out = self.think_json(prompt, ttl=10.0, task="rank_scan")
        ranked = out.get("ranked") or []
        if not ranked:
            return results
        order = {t: i for i, t in enumerate(ranked)}
        return sorted(results, key=lambda r: order.get(r["ticker"], 999))
